# Generated by Django 5.2 on 2025-04-18 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseConsolidada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=50, unique=True)),
                ('cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('esteira', models.CharField(blank=True, max_length=255, null=True)),
                ('esteira_regionalizada', models.CharField(blank=True, max_length=255, null=True)),
                ('seg_resumo', models.CharField(blank=True, max_length=255, null=True)),
                ('produto', models.CharField(blank=True, max_length=255, null=True)),
                ('servico', models.CharField(blank=True, max_length=255, null=True)),
                ('classificacao_resumo_atual', models.CharField(blank=True, max_length=255, null=True)),
                ('cadeia_pendencias_descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('carteira', models.CharField(blank=True, max_length=255, null=True)),
                ('dias_carteira_atual', models.IntegerField(blank=True, null=True)),
                ('data_tecnica', models.DateField(blank=True, null=True)),
                ('osx', models.CharField(blank=True, max_length=255, null=True)),
                ('motivo_pta_cod', models.CharField(blank=True, max_length=255, null=True)),
                ('wcd', models.CharField(blank=True, max_length=255, null=True)),
                ('num_atp', models.CharField(blank=True, max_length=255, null=True)),
                ('draft_encontrado', models.CharField(blank=True, max_length=255, null=True)),
                ('data_criacao_draft', models.DateField(blank=True, null=True)),
                ('tarefa_atual_draft', models.CharField(blank=True, max_length=255, null=True)),
                ('tecnologia_report', models.CharField(blank=True, max_length=255, null=True)),
                ('quebra_esteira', models.CharField(blank=True, max_length=255, null=True)),
                ('projetos', models.CharField(blank=True, max_length=255, null=True)),
                ('projetos_lote', models.CharField(blank=True, max_length=255, null=True)),
                ('tm_tec_total', models.CharField(blank=True, max_length=255, null=True)),
                ('delta_rec_liq', models.CharField(blank=True, max_length=255, null=True)),
                ('aging_resumo', models.CharField(blank=True, max_length=255, null=True)),
                ('origem_pend', models.CharField(blank=True, max_length=255, null=True)),
                ('segmento_v3', models.CharField(blank=True, max_length=255, null=True)),
                ('sla_tecnica', models.CharField(blank=True, max_length=255, null=True)),
                ('status_rede', models.CharField(blank=True, max_length=255, null=True)),
                ('eps_rede', models.CharField(blank=True, max_length=255, null=True)),
                ('data_rede', models.DateField(blank=True, null=True)),
                ('tipo_entrega', models.CharField(blank=True, max_length=255, null=True)),
                ('data_sae', models.DateField(blank=True, null=True)),
                ('agrupado', models.CharField(blank=True, max_length=255, null=True)),
                ('pendencia_macro', models.CharField(blank=True, max_length=255, null=True)),
                ('estimativa', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArquivoProcessado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo_arquivo', models.CharField(choices=[('REPORT_B2B', 'Report B2B'), ('REDE_EXTERNA', 'Rede Externa')], default='REPORT_B2B', max_length=50)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('data_processamento', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRevisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=50, unique=True)),
                ('status_anterior', models.CharField(max_length=255)),
                ('status_atual', models.CharField(max_length=255)),
                ('data_revisao', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
