# Generated by Django 5.2 on 2025-04-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processamento', '0002_alter_baseconsolidada_data_sae'),
        ('processamento', '0002_alter_delta_rec_liq_to_double'),
    ]

    operations = [
    ]
