# Generated by Django 5.2 on 2025-04-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamento', '0003_merge_20250419_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arquivoprocessado',
            options={'ordering': ['-data_processamento']},
        ),
        migrations.AddField(
            model_name='arquivoprocessado',
            name='mensagem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arquivoprocessado',
            name='registros_afetados',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arquivoprocessado',
            name='tempo_processamento',
            field=models.FloatField(blank=True, help_text='Tempo de processamento em segundos', null=True),
        ),
        migrations.AlterField(
            model_name='arquivoprocessado',
            name='tipo_arquivo',
            field=models.CharField(choices=[('REPORT_B2B', 'Report B2B'), ('REDE_EXTERNA', 'Rede Externa'), ('REGRAS_NEGOCIO', 'Regras de Negócio'), ('EXPORTACAO', 'Exportação de Base')], default='REPORT_B2B', max_length=50),
        ),
        migrations.AlterField(
            model_name='baseconsolidada',
            name='delta_rec_liq',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
