# Generated by Django 5.2 on 2025-04-19 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamento', '0005_perfilusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAlteracaoPendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(db_index=True, max_length=50)),
                ('valor_anterior', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_novo', models.CharField(max_length=100)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Alteração de Pendência',
                'verbose_name_plural': 'Logs de Alterações de Pendências',
                'ordering': ['-data_alteracao'],
            },
        ),
    ]
